# Read in data

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read in data
df = pd.read_csv('../Data/preprocessedData.csv')
df.head()

Age    Height     Weight  Veg_Consump  Water_Consump  Meal_Count  \
0  22.547298  1.722461  51.881263     2.663421       1.041110    3.000000   
1  19.799054  1.743702  54.927529     2.000000       2.847264    3.289260   
2  17.823438  1.708406  50.000000     1.642241       1.099231    3.452590   
3  19.007177  1.690727  49.895716     1.212908       1.029703    3.207071   
4  19.729250  1.793315  58.195150     2.508835       2.076933    3.435905   

   Phys_Act  Time_E_Dev  Gender_Female  Gender_Male  ...  Fam_Hist_no  \
0  0.794402    1.391948              1            0  ...            0   
1  1.680844    2.000000              0            1  ...            0   
2  0.418875    1.000000              1            0  ...            1   
3  2.000000    1.000000              1            0  ...            1   
4  2.026668    1.443328              0            1  ...            0   

   Fam_Hist_yes  H_Cal_Burn_no  H_Cal_Burn_yes  Transport_Automobile  \
0             1              1               0                     0   
1             1              1               0                     0   
2             0              1               0                     0   
3             0              1               0                     0   
4             1              1               0                     1   

   Transport_Bike  Transport_Motorbike  Transport_Public_Transportation  \
0               0                    0                                1   
1               0                    0                                1   
2               0                    0                                1   
3               0                    0                                1   
4               0                    0                                0   

   Transport_Walking    Body_Level  
0                  0  Body Level 1  
1                  0  Body Level 1  
2                  0  Body Level 1  
3                  0  Body Level 1  
4                  0  Body Level 1  

[5 rows x 32 columns]

## logisitic regression

In [3]:
#  see the accuracy before balancing the data
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# the target is Body_Level
X = df.drop('Body_Level', axis=1)
y = df['Body_Level']

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an LogisticRegression classifier
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(accuracy_score(y_test, y_pred)))

# classification report
print(classification_report(y_test, y_pred))


# Print the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy of logistic regression classifier on test set: 0.78
              precision    recall  f1-score   support

Body Level 1       0.84      0.83      0.84       136
Body Level 2       0.67      0.74      0.70       133
Body Level 3       0.75      0.69      0.72       143
Body Level 4       0.85      0.86      0.85       132

    accuracy                           0.78       544
   macro avg       0.78      0.78      0.78       544
weighted avg       0.78      0.78      0.78       544

Confusion Matrix:
[[113  23   0   0]
 [ 21  98  14   0]
 [  0  25  98  20]
 [  0   0  19 113]]


c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## SVM

In [4]:
from sklearn import svm
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# the target is Body_Level
X = df.drop('Body_Level', axis=1)
y = df['Body_Level']

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an SVM classifier
clf = svm.SVC(kernel='linear')

# Train the SVM classifier
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# classification report
print(classification_report(y_test, y_pred))

# Print the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.9338235294117647
              precision    recall  f1-score   support

Body Level 1       0.93      1.00      0.96       136
Body Level 2       0.95      0.89      0.92       133
Body Level 3       0.93      0.89      0.91       143
Body Level 4       0.93      0.96      0.95       132

    accuracy                           0.93       544
   macro avg       0.93      0.93      0.93       544
weighted avg       0.93      0.93      0.93       544

Confusion Matrix:
[[136   0   0   0]
 [ 10 118   5   0]
 [  1   6 127   9]
 [  0   0   5 127]]
